//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [Required(ErrorMessage = "Mã không để trống"), Key, DisplayName("Mã KH")]
        public int MaKH { get; set; }
        [Required(ErrorMessage = "tên không để trống"),  DisplayName("Tên KH"),StringLength(30,MinimumLength =2)]
        public string TenKH { get; set; }
        [Required(ErrorMessage = "Địa chỉ không để trống"), DisplayName("Địa chỉ"), StringLength(30, MinimumLength = 2)]
        public string Diachi { get; set; }
        [Required(ErrorMessage ="Giới tính không để trống")]
        public string Gioitinh { get; set; }
    }
}
